[package]
name = "aupp"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ed25519-dalek = { version = "3.0.0-pre.3", features = ["rand_core"] }
rand = { version = "0.9.2" }
