[package]
name = "eupp"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["eupp-core", "eupp-net"]

[dependencies]
eupp-core = { path = "./eupp-core" }
eupp-net = { path = "./eupp-net" }
tokio = { version = "1.0", features = ["full"] }
blake2 = "0.10.6"
hex = "0.4.3"
