[package]
name = "eupp-db"
version = "0.1.0"
edition = "2024"

[dependencies]
eupp-core = { path = "../eupp-core" }
redb = "3.1.0"
postcard = { version = "1.1", features = ["alloc"] }
serde = { version = "1.0" }
ethnum = { version = "1.5.2" }
