[package]
name = "eupp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local workspace crates
eupp-core = { path = "../eupp-core" }
eupp-rpc = { path = "../eupp-rpc" }
ed25519-dalek = { version = "3.0.0-pre.3", features = ["rand_core"] }
jsonrpsee = { version = "0.22", features = ["client"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
hex = "0.4"
anyhow = "1.0"
