[package]
name = "eupp-core"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = { version = "3.0.0-pre.3", features = ["rand_core"] }
hex = "0.4.3"
ethnum = { version = "1.5.2", features = ["serde"] }
