[package]
name = "eupp-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
eupp-core = { path = "../eupp-core" }
jsonrpsee = { version = "0.22", features = ["macros", "server", "client"] }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
